budget/urls.py
from django.contrib import admin
from django.urls import path,include
from .import views

urlpatterns = [

    path('',views.dashboard,name = 'dashboard'),
    path('add_budget',views.add_budget,name = 'add_budget'),
    path('edit_budget/<str:pk>',views.edit_budget,name = 'edit_budget'),
    path('delete_budget/<str:pk>',views.delete_budget,name = 'delete_budget'),
    path('add_actuals',views.add_actuals,name = 'add_actuals'),
    path('edit_actuals/<str:pk>',views.edit_actuals,name = 'edit_actuals'),
    path('delete_actuals/<str:pk>',views.delete_actuals,name = 'delete_actuals'),
    path('add_category',views.add_category,name = 'add_category'),
    path('monthly',views.monthly,name = 'monthly'),
    path('yearly',views.yearly,name = 'yearly'),
    path('category_manager',views.category_manager,name = 'category_manager'),
    path('edit_category/<str:pk>',views.edit_category,name = 'edit_category'),


    

    
]

budget_app/urls.py
from django.contrib import admin
from django.urls import path,include
#from budget_app.budget_app.settings import STATIC_ROOT, STATIC_URL
from register import views as v
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path("register/",v.register, name = 'register'),
    path("editProfile/",v.editProfile, name = 'editProfile'),
    path('',include('budget.urls')),
    path('',include("django.contrib.auth.urls")),
    path('reset_password/', auth_views.PasswordResetView.as_view(template_name = 'registration/password_reset.html')),
    path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(), name = "registration/password_reset_done" ),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name = "password_reset_confirm"  ),
    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(), name = "password_reset_complete"  ),
]


urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)


                      

budget/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.





class Category(models.Model):
    user = models.ForeignKey(User,on_delete=models.SET_NULL,null=True,blank =True)
    TYPE = (
            ('Income', 'Income'),
            ('Expense', 'Expense'),)
    category_feild =  models.CharField(max_length = 100,unique = False)
    income_or_expense = models.CharField(default =" ",max_length=200, choices=TYPE)

    def __str__(self):
        return self.category_feild



class Budget(models.Model):
    
    category = models.ForeignKey(Category,on_delete=models.CASCADE)
    date = models.DateTimeField(auto_now_add=False)
    budget_amt = models.FloatField(default= 0)
    comments = models.CharField(max_length = 140,default="")

    def __str__(self):

        return self.category.category_feild +' - ' + str(self.date.strftime('%b %Y'))



class Actuals(models.Model):
    
    category = models.ForeignKey(Category,on_delete=models.CASCADE)
    date = models.DateTimeField(auto_now_add=False)
    transactions_amount = models.FloatField()
    vendor = models.CharField(max_length = 255,default="")
    details = models.CharField(max_length = 255)

    def __str__(self):
        return self.category.category_feild

budget/forms.py
from inspect import Attribute
#from tkinter import Widget
from django.forms import ModelForm
from django import forms
from .models import Budget,Actuals,Category





class budget_form(ModelForm):

    def __init__(self,*args, user=None, **kwargs):
        super(budget_form, self).__init__(*args, **kwargs)
        if user is not None:
            self.fields['category'].queryset = Category.objects.filter(user=user)




    class Meta:
        model = Budget
        fields = ['category','date','budget_amt','comments' ]
        widgets = {
            
            'category' : forms.Select(attrs={'class':'form-control'}),
            'date' : forms.DateInput(attrs={'class':'form-control'}),
            'budget_amt' : forms.NumberInput(attrs={'class':'form-control'}),
            'comments' : forms.TextInput(attrs={'class':'form-control'}),
        }

class actuals_form(ModelForm):

    def __init__(self,*args, user=None, **kwargs):
        super(actuals_form, self).__init__(*args, **kwargs)
        if user is not None:
            self.fields['category'].queryset = Category.objects.filter(user=user)



    class Meta:
        model = Actuals
        fields = '__all__'

        widgets = {
            
            'category' : forms.Select(attrs={'class':'form-control'}),
            'date' : forms.DateInput(attrs={'class':'form-control'}),
            'transactions_amount' : forms.NumberInput(attrs={'class':'form-control'}),
            'vendor' : forms.TextInput(attrs={'class':'form-control'}),
            'details': forms.TextInput(attrs={'class':'form-control'}),
            
        }

class categories_form(ModelForm):
    
    
    class Meta:
        model = Category
        fields = '__all__'
        widgets = {'user': forms.HiddenInput()}


class date_form(forms.Form): 
    INTEGER_CHOICES = [('01','January'),('02', 'February'),('03','March'),('04','April'),('05','May'),('06','June'),('07','July'),('08','August'),('09','September'),('10','October'),('11','November'),('12','December')]
    YEAR_CHOICE = [('2019',2019),('2020', 2020),('2021',2021),('2022',2022),('2023',2023),('2024',2024)]

    months = forms.CharField(label='Month',required=False,widget=forms.Select(choices=INTEGER_CHOICES,attrs={'class':'form-control-sm'}))

    years = forms.CharField(label='Year',required=False,widget=forms.Select(choices=YEAR_CHOICE,attrs={'class':'form-control-sm'}))

 

class year_form(forms.Form):
    YEAR_CHOICE = [('2019',2019),('2020', 2020),('2021',2021),('2022',2022),('2023',2023),('2024',2024)]
    years = forms.CharField(label='Year',required=False,widget=forms.Select(choices=YEAR_CHOICE,attrs={'class':'form-control'}))

budget/views.py
from cgitb import html
from operator import sub
from unicodedata import category
from django.shortcuts import render,redirect
from django.http import HttpResponseRedirect, JsonResponse
import plotly
from .models import Budget,Actuals,Category
from .forms import budget_form, categories_form, actuals_form,date_form,year_form
from datetime import date, datetime
from django.db.models import Sum
import pytz
import numpy as np
import pandas as pd
import plotly.graph_objs as go
from plotly.offline import plot
import plotly.express as px
import plotly.offline as opy
from plotly.subplots import make_subplots
from django.core import serializers
from django.http import HttpResponse
import json
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required



# Create your views here.


def dashboard(request):

    return render(request,'budget/dashboard.html',{'Hello':'Hello'})

@login_required(login_url= 'login')
def add_budget(request):

    b_form = budget_form(user=request.user)
    if request.method == 'POST' and "budgetForminfo" in request.POST:
        
        b_form = budget_form(request.POST or None)
        
        if b_form.is_valid():
            
            b_form = budget_form(request.POST or None,request.FILES,user = request.user)
            b_form.save()
            b_form = budget_form()
            return redirect('add_budget')

    currentMonth = datetime.now().month
    currentYear = datetime.now().year
    
    m_text = ""
    y_text = ""

    
    d_form = date_form
    if request.method == 'POST' and "get_month" in request.POST:
        d_form = date_form(request.POST or None)
        if d_form.is_valid():
            m_text = d_form.cleaned_data['months']
            y_text = d_form.cleaned_data['years']

    
    if not m_text:
       monthForsearch = '{:02d}'.format(currentMonth)
       yearForsearch = str(currentYear)
    else:
        monthForsearch = m_text
        yearForsearch = y_text

    
    income = Budget.objects.filter(category__user = request.user,category__income_or_expense = 'Income',date__year = yearForsearch, date__month = monthForsearch)
    expense = Budget.objects.filter(category__user = request.user,category__income_or_expense = 'Expense',date__year = yearForsearch, date__month = monthForsearch)

    tot_inc = Budget.objects.filter(category__user = request.user,category__income_or_expense = 'Income',date__year = yearForsearch, date__month = monthForsearch).aggregate(Sum('budget_amt'))
    tot_exp = Budget.objects.filter(category__user = request.user,category__income_or_expense = 'Expense',date__year = yearForsearch, date__month = monthForsearch).aggregate(Sum('budget_amt'))

    templateMonth = str(int(monthForsearch))
    datetime_object = datetime.strptime(templateMonth, "%m")
    month_name = datetime_object.strftime("%B")




    if len(income) == 0 or len(expense) == 0 :

        error  = 'Please Budget Income & Expense to see data'

        return render(request,'budget/add_budget.html',{'b_form':b_form,'error':error,'d_form':d_form,'yearForsearch':yearForsearch,'month_name':month_name,'expense':expense,'income':income})

    


    saved = tot_inc['budget_amt__sum'] - tot_exp['budget_amt__sum']

    tot_saved = "{:,.2f}".format(saved)
    tot_inc_float = "{:,.2f}".format(tot_inc['budget_amt__sum'])
    tot_exp_float = "{:,.2f}".format(tot_exp['budget_amt__sum'])


    

    

    


    return render(request,'budget/add_budget.html',{'b_form':b_form,'d_form':d_form,'expense':expense,'income':income,'monthForsearch':monthForsearch, 'month_name':month_name, 'yearForsearch':yearForsearch,'tot_inc': tot_inc_float,'tot_exp':tot_exp_float,'tot_saved':tot_saved})

@login_required(login_url= 'login')
def edit_budget(request,pk):

    budLine = Budget.objects.get(id=pk)
    editBudgetform = budget_form(instance = budLine,user=request.user )
    if request.method == 'POST' and "editBudgetform" in request.POST:
        editBudgetform = budget_form(request.POST or None,instance = budLine)
        if editBudgetform.is_valid():
                editBudgetform = budget_form(request.POST or None,request.FILES, user=request.user,instance = budLine)
                editBudgetform.save()
                editBudgetform = budget_form()
                return redirect('add_budget')
        
    return render(request,'budget/edit_budget.html',{'editBudgetform':editBudgetform})

@login_required(login_url= 'login')
def delete_budget(request,pk):
    budDel = Budget.objects.get(id=pk)
    budDel.delete()
    return redirect('add_budget')

@login_required(login_url= 'login')
def add_actuals(request):

    currentMonth = datetime.now().month
    currentYear = datetime.now().year

    text = ""
    y_text = ""

    
    d_form = date_form
    if request.method == 'POST' and "get_month" in request.POST:
        d_form = date_form(request.POST or None)
        if d_form.is_valid():
            text = d_form.cleaned_data['months']
            y_text = d_form.cleaned_data['years']

    
    if not text:
       monthForsearch = '{:02d}'.format(currentMonth)
       yearForsearch = str(currentYear)
    else:
        monthForsearch = text
        yearForsearch = y_text


    income_act = Actuals.objects.filter(category__user = request.user,category__income_or_expense = 'Income',date__year = yearForsearch, date__month = monthForsearch)
    expense_act = Actuals.objects.filter(category__user = request.user,category__income_or_expense = 'Expense',date__year = yearForsearch, date__month = monthForsearch)

    

    form = actuals_form(user=request.user)
    if request.method == 'POST' and "actuals_form" in request.POST:
        form = actuals_form(request.POST)
        if form.is_valid():
            form = actuals_form(request.POST or None,request.FILES, user=request.user)
            form.save()
            form = actuals_form()
            return redirect('add_actuals')


    templateMonth = str(int(monthForsearch))
    datetime_object = datetime.strptime(templateMonth, "%m")
    month_name = datetime_object.strftime("%B")

    return render(request,'budget/add_actuals.html',{'d_form':d_form,'form':form,'income_act':income_act,'expense_act':expense_act, 'month_name':month_name, 'yearForsearch':yearForsearch})

@login_required(login_url= 'login')
def edit_actuals(request,pk):

    
    actLine = Actuals.objects.get(id=pk)
    editActualsform = actuals_form(instance = actLine,user=request.user)

    if request.method == 'POST' and "editActualsform" in request.POST:
        editActualsform = actuals_form(request.POST or None,instance = actLine)
        if editActualsform.is_valid():
            editActualsform = actuals_form(request.POST or None,request.FILES, user=request.user,instance = actLine)
            editActualsform.save()
            editActualsform = actuals_form()
            return redirect('add_actuals')

    
    return render(request,'budget/edit_actuals.html',{'editActualsform':editActualsform})


@login_required(login_url= 'login')
def delete_actuals(request,pk):
    actDel = Actuals.objects.get(id=pk)
    actDel.delete()
    return redirect('add_actuals')

@login_required(login_url= 'login')
def add_category(request):

    form = categories_form

    if request.method == 'POST':
        form = categories_form(request.POST)
        if form.is_valid():
            form.save(commit= False)
            form.instance.user = request.user
            form.save()
            return redirect('add_budget')

    

    return render(request,'budget/add_category.html',{'form':form})


@login_required(login_url= 'login')
def monthly(request):


    currentMonth = datetime.now().month
    currentYear = datetime.now().year
    
    text = ""
    y_text = ""

    
    d_form = date_form
    if request.method == 'POST' and "get_month" in request.POST:
        d_form = date_form(request.POST or None)
        if d_form.is_valid():
            text = d_form.cleaned_data['months']
            y_text = d_form.cleaned_data['years']

    
    if not text:
       monthForsearch = '{:02d}'.format(currentMonth)
       yearForsearch = str(currentYear)

    else:
        monthForsearch = text
        yearForsearch = y_text



    act_exp = Actuals.objects.filter(category__user = request.user,category__income_or_expense = 'Expense', date__year = yearForsearch ,date__month = monthForsearch).values('category__category_feild','date').order_by('category__category_feild').annotate(total_actuals = Sum('transactions_amount'))
    act_inc = Actuals.objects.filter(category__user = request.user,category__income_or_expense = 'Income', date__year = yearForsearch ,date__month = monthForsearch).values('category__category_feild','date').order_by('category__category_feild').annotate(total_actuals = Sum('transactions_amount'))
        
    bud_exp =  Budget.objects.filter(category__user = request.user,category__income_or_expense = 'Expense',date__year = yearForsearch, date__month = monthForsearch).values('category__category_feild','date','comments').annotate(total_budget = Sum('budget_amt'))
    bud_inc = Budget.objects.filter(category__user = request.user,category__income_or_expense = 'Income',date__year = yearForsearch, date__month = monthForsearch).values('category__category_feild','date','comments').annotate(total_budget = Sum('budget_amt'))


    # to grab actual expanses

    act_exp_Category = []
    act_exp_Date = []
    act_exp_Actual = []


    for i in range(0,len(act_exp)):
        act_exp_Category.append(act_exp[i]['category__category_feild'])
        act_exp_Date.append(act_exp[i]['date'])
        act_exp_Actual.append(act_exp[i]['total_actuals'])

        
        
    act_exp_df = pd.DataFrame({'Category' : act_exp_Category, 'Actual': act_exp_Actual,'Date': act_exp_Date })

    act_exp_final = pd.DataFrame(act_exp_df.groupby('Category')['Actual'].sum())



        # to grab actual income

    act_inc_Category = []
    act_inc_Date = []
    act_inc_Actual = []

budget/templates/budget/add_actuals.html
{% extends 'budget/base.html' %}



{% block content %}

<div class="container">
<form method = "Post" class = 'card p-3 bg-light'>
    <h4>Enter Transactions</h4>

    <a style="float:left" href="{%url 'add_category'%}"><button type="button" class="btn btn-primary btn-sm"> + Add Category </button></a>
    
    <div class="form-group">  

    {% csrf_token %}

    {{form}}

    <input style="width:100%" class="btn btn-primary" type="submit" name = "actuals_form">
    </div>
</form>

<div class="d-flex p-2"></div>


<form enctype= multipart/form-data method = "Post" class = 'card p-3 bg-light'>
    <h4>Find Transaction</h4>

    {% csrf_token %}

    {{d_form}}

    <input class="btn btn-primary" type="submit"  name="get_month">
    
</form>

<div class="d-flex p-2 bd-highlight"></div>


<h3>{{month_name}} {{yearForsearch}} Transactions Detail</h3>


<table class="table table-striped">
    <tr class="d-flex">
    <caption style="caption-side: top" ><strong>Income</strong></caption>

    <th class="col-1">Category</th>
    <th class="col-1">Date</th>
    <th class="col-1">Actual Amount</th>
    <th class="col-1">Vendor</th>
    <th class="col-1" >Details</th>
    <th class="col-1"></th>
    <th class="col-1"></th>
    </tr>
    <tr>
{% for income_act in income_act %}        
    <td class="col-1">{{income_act.category}}</td>
    <td class="col-1">{{income_act.date|date:"M d Y"}}</td>
    <td class="col-1">{{income_act.transactions_amount}}</td>
    <td class="col-1">{{income_act.vendor}}</td>
    <td class="col-1">{{income_act.details}}</td>
    <td class="col-1"><a href="{% url 'edit_actuals' income_act.id %}"> Edit</a></td>
    <td class="col-1"><a href="{% url 'delete_actuals' income_act.id %}"> Delete</a></td>
    </tr>
{% endfor %}

</table>



<table class="table table-striped">
    <tr class="d-flex">
    <caption style="caption-side: top" ><strong>Expenses</strong></caption>
    <th class="col-1">Category</th>
    <th class="col-1">Date</th>
    <th class="col-1">Actual Amount</th>
    <th class="col-1">Vendor</th>
    <th class="col-1">Details</th>
    <th class="col-1"></th>
    <th class="col-1"></th>
    </tr>
    <tr>

{% for expense_act in expense_act %}        
    <td class="col-1">{{expense_act.category}}</td>
    <td class="col-1">{{expense_act.date|date:"M d Y"}}</td>
    <td class="col-1">{{expense_act.transactions_amount}}</td>
    <td class="col-1">{{expense_act.vendor}}</td>
    <td class="col-1">{{expense_act.details}}</td>
    <td class="col-1"><a href="{% url 'edit_actuals' expense_act.id %}"> Edit</a></td>
    <td class="col-1"><a href="{% url 'delete_actuals' expense_act.id %}"> Delete</a></td>
    </tr>
    {% endfor %}
    
</table>

</div>

<script>
      $(function () {
        $("#id_date").datepicker();
      });
    </script>

{% endblock content %}

budget/templates/budget/add_budget.html
{% extends 'budget/base.html' %}


{% block content %}

<div class = 'warning'>
  {{error}}
</div>



<div class="container">
<form enctype= multipart/form-data method = "Post" class = 'card p-3 bg-light'>
    <h4>Enter your budget</h4>

    <a style="float:left" href="{%url 'add_category'%}"><button type="button" class="btn btn-primary btn-sm"> + Add Category </button></a>
    <div class="form-group"> 

{% csrf_token %}

{{b_form}}

<input class="btn btn-primary" style="width:100%" type="submit" name ="budgetForminfo">

</form>
</div>

<div class="d-flex p-2"></div>


<form enctype= multipart/form-data method = "Post" class = 'card p-3 bg-light'>

<h4>Search for a budget</h4>

{% csrf_token %}

{{d_form}}

<input class="btn btn-primary" type="submit" name="get_month">

</form>

<div class="d-flex p-2 bd-highlight"></div>

<h3>{{month_name}} {{yearForsearch}} Budget </h3>

<div class="container">
    <div class="shadow-lg p-3 mb-5 bg-white rounded">
    
    <div class="card-group">
      <div class="card">
        
        <div class="card-body">
          <h5 class="card-title">Budgeted Income</h5>
          <h4 class="card-text">$ {{tot_inc}}</h4>
          
        </div>
      </div>
      
    
      <div class="card">
        
        <div class="card-body">
          <h5 class="card-title">Budgeted Expenses</h5>
          <h4 class="card-text">$ {{tot_exp}}</h4>
          
        </div>
      </div>
      
      <div class="card">
       
        <div class="card-body">
          <h5 class="card-title">Net Income</h5>
          <h4 class="card-text">$ {{tot_saved}}</h4>
         
        </div>
      </div>
    </div>
    </div>
    </div>


    <table class="table table-striped">
        <tr>
    
        <caption style="caption-side: top" ><b>Income</b></caption>
    
        <th class="col-1">Category</th>
        <th class="col-1">Date</th>
        <th class="col-1">Budget</th>
        <th class="col-1">Comments</th>
        <th class="col-1"></th>
        <th class="col-1"></th>
        </tr>
        <tr>
    {% for income in income %}       
        <td class="col-1" >{{income.category}}</td>
        <td class="col-1">{{income.date|date:"M d Y"}}</td>
        <td class="col-1">{{income.budget_amt}}</td>
        <td class="col-1">{{income.comments}}</td>
        <td class="col-1" ><a href="{% url 'edit_budget' income.id %}" > Edit</a></td>
        <td class="col-1"><a href="{% url 'delete_budget' income.id %}"> Delete</a></td>
        </tr>
        {% endfor %}
    
    </table>


    <table class="table table-striped">

        <tr>
    
        <caption style="caption-side: top" ><b>Expense</b></caption>
        <th class="col-1">Category</th>
        <th class="col-1">Date</th>
        <th class="col-1">Budget</th>
        <th class="col-1">Comments</th> 
        <th class="col-1"></th>
        <th class="col-1"></th>
        </tr>
        <tr>
     {% for expense in expense %}       
        <td class="col-1">{{expense.category}}</td>
        <td class="col-1">{{expense.date|date:"M d Y"}}</td>
        <td class="col-1">{{expense.budget_amt}}</td>
        <td class="col-1" >{{expense.comments}}</td>
        <td class="col-1" ><a href="{% url 'edit_budget' expense.id %}"> Edit </a></td>
        <td class="col-1"><a href="{% url 'delete_budget' expense.id %}"> Delete </a></td>
        </tr>
        {% endfor %}
    </table>

    <script>
      $(function () {
        $("#id_date").datepicker();
      });
    </script>
    

    {% endblock content %}

budget/templates/budget/add_category.html
{% extends 'budget/base.html' %}

{% block content %}

<div class="card">
<form method = "Post" class = 'card p-3 bg-light'>
    <div class="form-group" > 

    {% csrf_token %}

    {{form}}

    <input type="submit">
    </div>
</form>
</div>




{% endblock %}

budget/templates/budget/category_manager.html
{% extends 'budget/base.html' %}

{% block content %}


<h2>Manage Your Catagories</h2>



<div class="card">

<table class="table table-striped">
    <tr>


    <th scope="col">Category</th>
    <th scope="col">Income or Expense</th>
    <th scope="col">Edit</th>
  
    
    </tr>
    <tr>
        {%for cats in cats%}       
    <td>{{cats.category_feild}}</td>
    <td>{{cats.income_or_expense}}</td>
    <td><a href="{% url 'edit_category' cats.id %}" > Edit</a></td>
 
    </tr>
    {% endfor %}

</table>

</div>



{% endblock %}

budget/templates/budget/dashboard.html
<!---->
<!DOCTYPE html>
<nav class="navbar navbar-dark bg-primary ">

	

		<div class="col-md-12 bg-primary">

		{% if request.user.is_authenticated%}
		<a href= "/logout">		
		<button  type="button" class="btn btn-info btn-rounded ">Logout</button>
		</a>
		{% else %}
		<a href= "/login">		
		<button  type="button" class="btn btn-info btn-rounded ">Login</button>
		</a>
		{% endif %}

		<a href= "/register">
		<button  type="button" class="btn btn-success btn-rounded ">Sign Up !</button>
		</a>

		<div class="h-10 d-flex align-items-center justify-content-center">
			
			  <h1>SimpleBudgetAPP</h1>
			
		</div>

		

		</div>

	
	
	</nav>

<div class="jumbotron jumbotron-fluid">



    <div class="container">

      <h1 class="display-4">Welcome To the Budgeting App {{request.user.get_full_name}}</h1>
      <p class="lead">A simple app for full control of your finances</p>
    </div>
  </div>
<html><head>
	<title>
	
	</title>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
	<!--<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>-->
	<!--<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>-->
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
	<style type="text/css">
		.btn-circle.btn-xl {
			width: 200px;
			height: 200px;
			padding: 13px 18px;
			border-radius: 60px;
			font-size: 22px;
			text-align: center;
		}
	</style>
</head>
<body>
	<div class="container">
		
	<h1>What would you like to do.....</h1>
	
	<div class="container"></div>

    
    <a href="{%url 'add_budget'%}">
	<button type="button" class="btn btn-success btn-circle btn-xl"><b>Make a Budget</b></button>
    </a> 

    <a href="{%url 'add_actuals'%}">
	<button type="button" class="btn btn-secondary btn-circle btn-xl"><b>Add Transaction</b></button>
    </a>

    <a href="{%url 'monthly'%}">
	<button type="button" class="btn btn-primary btn-circle btn-xl"><b>See Monthly Dashboard</b></button>
    </a>
	<a href="{%url 'yearly'%}">
	<button type="button" class="btn btn-danger btn-circle btn-xl"><b>See Year to Date Dashboard</b></button>
	</a>
	</div>
	</div>
	</body>
</html>		

<!---->

budget/templates/budget/edit_actuals.html
{% extends 'budget/base.html' %}

{% block content %}

<h3> Edit Actuals</h3>

<form  method = "Post" class = 'card p-3 bg-light'>

    {% csrf_token %}

    {{editActualsform}}

    <input type="submit" value= 'Save' name="editActualsform">
    
</form>



{% endblock %}

budget/templates/budget/edit_budget.html
{% extends 'budget/base.html' %}

{% block content %}

<h3> Edit Budget</h3>

<form  method = "Post" class = 'card p-3 bg-light'>

{% csrf_token %}

{{editBudgetform}}

<input type="submit" value= 'Save' name="editBudgetform">

</form>



{% endblock content %}

budget/templates/budget/edit_category.html
{% extends 'budget/base.html' %}

{% block content %}




<form  method = "Post" class = 'card p-3 bg-light'>

    {% csrf_token %}
    
    {{editCatform}}
    
<input type="submit" value= 'Save' name="editCatform">
    




{% endblock content %}